version: 0.1

environment_variables:
  plaintext:
    NODE_ENV: "test"
    FACEBOOK_ACCESS_TOKEN: "EAADrtGM4WtkBAPmNI7uQpcFH1fVaDTUG7RS9ae3XZBt4KGQm5oE8Q8GrFWAEEap9hhhrIsC9qvdJ2SMWmNyvHxavAxQ1nRLSuupevoZC1QwDqxZApZBegOmX3g5XJRQ4bhkvV7GBsvm1c8DdMlFfJwmLN7qpJZCIYEOS08ylXqBZApeoCiQnG6NNeeiTqwZCTkUcHjYdTj3ewZDZD"
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test