version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:8.0
    # circleci/node:8.4.0 사용 시 버전 문제 발생(Cannot find module 'npmlog')
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.   
      - image: mongo:3.4.7
    steps:
      - checkout
      - run:
          name: upgrade-npm
          command: 'sudo npm upgrade'
      - run:
          name: install-yarn
          command: 'sudo npm install yarn -g'
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - restore_cache:
          keys: 
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - v1-cache-{{ .Branch }}-{{ checksum "package.json" }}
            # Find the most recent cache used from any branch
            - v1-cache-{{ .Branch }}
            - v1-cache
      - run:
          name: yarn
          command: 'sudo yarn install'
      - save_cache:
          key: v1-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: v1-cache-{{ .Branch }}
          paths:
            - ./node_modules
      - save_cache:
          key: v1-cache
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov yarn test'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml